schema_version = 1
name = "native"
version = "2026.7.16.3"

[base]
repository = "https://github.com/henrikkvamme/devme-native-template.git"
revision = "cdc77e4ba742bc0fcbfb745c604dbf6e4772aee6"
subdir = "."
