schema_version = 1
name = "native"
version = "2026.7.16.4"

[base]
repository = "https://github.com/henrikkvamme/devme-native-template.git"
revision = "472aff1ab47bd5bef7bceb90f84bd325a04d55ad"
subdir = "."
